### PR TITLE
Change color scheme to base16-brewer

### PR DESCRIPTION
**Pull request by tmad40blue**
Changed the color scheme of the page to base16-brewer (https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-brewer.sh). The base16 color schemes are carefully selected and offer a superior look-and-feel to what they're applied on.

Other available base16 color schemes can be previewed here: https://chriskempson.github.io/base16/

### CODE REVIEW

**Comment by marlyn-x86** [comment]
Could you please provide a picture of the website before and after your color adjustment, for comparison?

**Comment by Regen1** [comment]
Sorry for not getting to this sooner, I swear I've set this to email me whenever something pops up, but apparently my spambox failed me.

Could you please show some pictures of how it looks?

**Comment by tigercat2000** [comment]
@tmad40blue Hey, could we get your permission to re-license the html and css files under the MIT license? Since you've already had a PR merged, have to get your go-ahead along with myself and @Regen1's.

**Comment by Regen1** [comment]
This PR no longer fits the current website

**Pull request closed without merging**
