### PR TITLE
Dynamic rules page

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
[forum thread](https://nanotrasen.se/forum/topic/11155-change-code-for-the-rules-every-3-days/). This is a new rules page that has a manually set "secret words" for normal usage, but can be randomized for ban appeals. Going to http://nanotrasen.se/rules.php will give you a set of rules with "emulated feelings" in the exact same place every time.

But let's say user "Test" gets banned. Then you'd give Test this link: http://nanotrasen.se/rules.php?seed=Test, which would pick two random words based on their username, in this case, "Exit Tray", and then insert "Adminhelping the words Exit Tray will let us know you've read the rules" randomly into the rules. The secret sentence only goes into rules that are marked as "can_have_secret_words", so it won't be at the very beginning or at the very end. Currently it's set to rules 8, 9, and 10.

If user "Test" gets banned again, and you want them to reread the rules, just give them a link with a different seed, maybe http://nanotrasen.se/rules.php?seed=Test2 or something, and they'll have to refind new secret words in a new place.

Rules and potential secret words are in `rules.json`.

Searching for "Adminhelping the words" and "will let us know you've read the rules" is disabled through javascript, but the secret words themselves are not, so an admin can easily verify that the secret words are correct by using command/control F.

Here's what a rule with the secret words looks like:
rule9

### CODE REVIEW

**Comment by Regen1** [comment]
Apologies that I could not get to this sooner, the github page refuses to send me emails regarding this particular repo.

While it's certainly interesting what you've done, I'm not sure how appliable it is to us, I'll have to talk to the headmins and other server devs to see what they think. 

I'll get back to this PR ASAP, if I for some reason take longer than expected don't feel shy to shoot me a message on discord.

Regen#3409

**Comment by Tayyyyyyy** [comment]
Yup! No worries, I know that you may not want to be this harsh, though providing no seed will result in the same behavior as before (just a little more inconvenient to edit the rules as a json as opposed to a forum post).

I did PM Neca about it earlier but he probably hasn't had a chance to look at this yet.

**Comment by Regen1** [comment]
Okay, talking to our other maintainers and heads about this, we have some concerns

JS being completely clientsided, it won't really stop people from CTRL+F searching if they want to, although it will probably stop most people.

The JSON file needed would be rather large, and it would require any and all changes to the rules to go through that JSON file and be merged within this github, that's a lot more steps to go through than we currently have.

The JSON file will not have any specific editing tools, meaning everything must be done purely in HTML, on the forums we have editing tools for the text to quickly change how it looks

The admins have to manually find the words themselves, and it's a randomized location between rules 8 and 10.

**Comment by Tayyyyyyy** [comment]
> JS being completely clientsided, it won't really stop people from CTRL+F searching if they want to, although it will probably stop most people.

Never done php before, so if you have pointers for how to improve this, I could definitely give it a try! Maybe dynamically generate the text as image?? Though that may be overkill 🤔

> JSON concerns

If this is a thing that the admins want, I think it should be possible to write some php that can parse the rules forum page into this page! The rules json was mostly the fastest way I could think of...

> The admins have to manually find the words themselves, and it's a randomized location between rules 8 and 10.

The idea is that it's a one way thing. You have to find the words manually, but verifying that the words are correct is fast, because ctrl-f searching isn't disabled for the secret words. Hopefully that makes sense? So you probably don't wanna bother looking for the words beforehand, but after the person finds it, you can check that the words are the right ones pretty fast.

**Comment by Regen1** [comment]
My issue with this is that it might try to solve a problem we don't really have, it does make "CTRL + F" searching for the rules slightly harder, but we've already got people who can't find the secret word, so I'd say our current method is largely effective.

This seems to over-complicate things, and I'm not sure if it's the direction we want to take.

**Comment by Tayyyyyyy** [comment]
Okay, I figured the current system is pretty good for the vast majority of cases. If you don't think it's worth it to make this sync up with the forum post, let me know and I'll close the PR. Otherwise I'll probably put it in in the next few weeks or so

**Comment by Regen1** [comment]
Yeah, while I like the initiative, I'm not sure if this is actually needed, don't fix what's not broken and whatnot.

Thank you for the effort though, greatly appreciated!

**Comment by Tayyyyyyy** [comment]
PHP sucks anyway 🙂 Thanks for looking at it!

**Pull request closed without merging**
